### ISSUE TITLE
Exclusion filters don't seem to operate

### ISSUE THREAD

**Issue by tdsmith** [jasperapp/jasper#10]
Searching my inbox or my repo streams for `is:unread is:open -author:ilovezfs` shows me a lot of PRs that were authored by user ilovezfs. This exclusion works [on Github](https://github.com/Homebrew/brew/pulls?utf8=%E2%9C%93&q=is%3Aopen%20-author%3Ailovezfs%20) but not in Jasper.

**Comment by h13i32maru** [comment]
@tdsmith Thanks! The feature is nice! I will try to implement it.

**Comment by h13i32maru** [comment]
@tdsmith  I released v0.2.1-beta.1 and support exclusion filter 😄 
https://jasperapp.io/beta.html
