### ISSUE TITLE
Ignoring activity that done by myself 

### ISSUE THREAD

**Issue by kibitan** [jasperapp/jasper#11]
Hi! thanks such a nice issue tracker! now Im using as trial and i like it now.
one thing i want to request to adding a option that Ignoring activity that done by myself.
when i did comment/self-assign etc,, stream also updated that and it looks noise for me...

how do you think my proposal?

**Comment by h13i32maru** [comment]
@kibitan Thanks and sorry for late reply 😓 

Now, Jasper ignores self activites. Howerver can not ignore it by unknown reason in sometimes...
So I am having trouble with the problem.

**Comment by kibitan** [comment]
@h13i32maru oh okay, I'm rooting for fixing it.

**Comment by h13i32maru** [comment]
v0.3.0 was out! Please check it.
https://jasperapp.io/release.html

**Comment by kibitan** [comment]
@h13i32maru  super cooool! thanks 😄

**Comment by alloy** [comment]
@h13i32maru I’m on v0.7.0 and have noticed this issue again, so there seems to be a regression. Would you like me to open a new issue or re-open this one?
