### ISSUE TITLE
Request: the same download URL except for the version string

### ISSUE THREAD

**Issue by jfut** [jasperapp/jasper#137]
I am a user of [Scoop](https://scoop.sh/), a package manager for Windows.

The v0.9.0 download URL has been changed to Dropbox. Will the `91eka4flfomuvxa` part be the same in the future?
https://www.dropbox.com/s/91eka4flfomuvxa/jasper_v0.9.0_windows.zip?dl=1

Scoop can automatically update the software versions in the manifest, used for package management information, using the `autoupdate` function. The manifest for Japser is as follows:
https://github.com/lukesampson/scoop-extras/blob/master/bucket/jasper.json

Before v0.8.0, the download URL were identical except for the version string, so the `autoupdate` worked fine.

```
"url": "https://github.com/jasperapp/jasper/releases/download/v$version/jasper_v$version_windows.zip"
```

If the `91eka4flfomuvxa` part of the Dropbox URL changes each new version, I'd be happy to download it from GitHub as before.

Appendix: How to mange a version of Jasper by Scoop:

```
# user: Install jasper
> scoop install jasper

# maintener: Update version in manifest (Run only the manifest maintainer and push to the bucket(repository))
> ./checkver.ps1 -u jasper

# user: Update jasper
> scoop update jasper
```

**Comment by h13i32maru** [comment]
> Will the 91eka4flfomuvxa part be the same in the future?

It is random URL by Dropbox.

>  I'd be happy to download it from GitHub as before.

I have uploaded the binaries to the GitHub release. I will upload it after this 👍 
https://github.com/jasperapp/jasper/releases/tag/v0.9.0

**Comment by jfut** [comment]
Thanks for uploading!
