### ISSUE TITLE
When edit the STREAMS, broken display

### ISSUE THREAD

**Issue by suzuki** [jasperapp/jasper#14]
### 1. Edit some STREAM

<img width="275" alt="2016-07-06 09 59 00" src="https://cloud.githubusercontent.com/assets/10488/16604494/04b6a9fa-4361-11e6-81a5-644e9fadc71e.png">

### 2. Press OK

<img width="488" alt="2016-07-06 09 59 16" src="https://cloud.githubusercontent.com/assets/10488/16604512/2bbe6cf4-4361-11e6-8a30-8d734328b3ed.png">

### 3. Broken

<img width="257" alt="2016-07-06 09 59 32" src="https://cloud.githubusercontent.com/assets/10488/16604516/370a562c-4361-11e6-86f5-a6b5240f1e20.png">

- I need to restart Jasper.

## Version
- Version 0.1.2
  - Trial version

**Comment by h13i32maru** [comment]
@suzuki Thanks! I will inspect it.

**Comment by h13i32maru** [comment]
@suzuki  I released v0.2.1-beta.1 and fix this bug 😄 
https://jasperapp.io/beta.html

**Comment by suzuki** [comment]
@h13i32maru I tried v0.2.1-beta.1.  It was perfect. Thx ! 👍

**Comment by lestrrat** [comment]
I still seem to get this, and I have Jasper 0.2.5 installed
