### ISSUE TITLE
Closed issues still show up despite filter

### ISSUE THREAD

**Issue by stevage** [jasperapp/jasper#15]
As you can see I have a filter with `is:open`. It initially shows only open issues. But when issues become closed, they still remain in this list.

![closed](https://cloud.githubusercontent.com/assets/678344/16675751/4430b506-4507-11e6-816b-fa5f4b0e4361.png)

**Comment by h13i32maru** [comment]
@stevage Thanks for this issue.

The behavior is specification of Jasper. And changing it is very difficult...
Please use `is:open`  in filter.

**Comment by h13i32maru** [comment]
> Are you sure you understood my bug report?

Yes, I understood your report. This is internal behavior.

For example:
- You made the streams:
  - `MyOpenIssues` with `is:open author:yourName`
  - `MyIssues` with `author:yourName`
- You create issue#123
- Jasper relates issue#123 with the both streams.
- After that, the issue#123 is closed. However the issue#123 has been related with both streams.
- If the issue#123 is updated, `MyIssues` catches the updating of issue#123 and updates internal state of the issue#123 in Jasper
- The issue#123 rises in `MyOpenIssues`
