### ISSUE TITLE
Application crashes if you try to open a file

### ISSUE THREAD

**Issue by fatcomma** [jasperapp/jasper#17]
If you click on a link to a file attachment from anywhere in Jasper the application will immediately crash :cry:. 

You can reproduce this behavior by opening this issue in Jasper and clicking on the link :point_down:.

[pdf-sample.pdf](https://github.com/jasperapp/jasper/files/404409/pdf-sample.pdf)

**Comment by h13i32maru** [comment]
@fatcomma Thanks for this issue.
I will fix it.

**Comment by fatcomma** [comment]
@h13i32maru :+1:. Thanks for creating Jasper :heart:!

**Comment by h13i32maru** [comment]
I released Jasper v0.2.0 at now! And fixed this bug.
Please download and use it 👍 
https://jasperapp.io/release.html
