### ISSUE TITLE
JavaScript error with Master code

### ISSUE THREAD

**Issue by Watson1978** [jasperapp/jasper#177]
When click `^` or `v`  button without search word, it shows "JavaScript error occurred" dialog.

![screen 2020-09-29 21_01_03](https://user-images.githubusercontent.com/199156/94555842-22143900-0297-11eb-8021-888bed554726.gif)

**Comment by h13i32maru** [comment]
Thanks. And fixed it https://github.com/jasperapp/jasper/commit/3fa244a4df367cd2f3022e775c10271b39642d27
