### ISSUE TITLE
Separete themes per main view and build-in browser

### ISSUE THREAD

**Issue by micnncim** [jasperapp/jasper#186]
Thank you for the awesome app!

I like Jasper's dark mode very much. I'd like to use dark mode for the main view and light mode for the build-in browser like below. Could Jasper support it?

![jasper-light-and-dark](https://user-images.githubusercontent.com/21333876/95968489-764b1b80-0e48-11eb-9046-bcd6bc3c729d.png)

**Comment by h13i32maru** [comment]
The option is supported. `Enable theme mode on GitHub/GHE`
<img width="541" alt="スクリーンショット 2020-10-14 18 47 36" src="https://user-images.githubusercontent.com/985170/95972858-ea3bf280-0e4d-11eb-9efd-b410f21b3b75.png">

**Comment by micnncim** [comment]
Oops, I didn't notice that 🙇‍♂️ Cool, thank you!
