### ISSUE TITLE
Freeze when selecting item link clicked

### ISSUE THREAD

**Issue by morishin** [jasperapp/jasper#19]
Jasper freezes when *selecting item* link clicked.
<img width="800" alt="kill_button" src="https://cloud.githubusercontent.com/assets/1413408/17687702/71cb0d58-63b2-11e6-95c9-4d1e9073f82c.png">

**Comment by h13i32maru** [comment]
I released Jasper v0.2.0 at now! And fixed this bug.
Please download and use it 👍 
https://jasperapp.io/release.html

**Comment by morishin** [comment]
🆒 🆒 🆒
