### ISSUE TITLE
On setup, "invalid setting" displays with GHE

### ISSUE THREAD

**Issue by hdkshjm** [jasperapp/jasper#2]
Hi,

I have tried to setup jasper with our GHE(http://our-ghe/), but  "invalid setting" displays.
I have checked our GHE log files, but there is no rest api access log from jasper of my client pc.

If I access GHE rest api using curl command, the access log exists on our GHE.
- curl command:  
``` 
curl -s http://our-ghe/api/v3/user/orgs?access_token=aaaaaabbbbbccccc 
```
- access log on our GHE: 
``` 
admin@our-ghe:/var/log$ cat nginx/github.log|grep "/api/v3/user/orgs"
127.0.0.1 - - [08/Jun/2016:12:40:19 +0900] "GET /api/v3/user/orgs?access_token=aaaaaabbbbbccccc HTTP/1.1" 200 4901 "-" "curl/7.43.0" "192.168.1.100" 0.052 0.052 .  
```

Could you tell me how to solve "invalid setting" ?

### Our env
- client pc: Mac OS Yosemite
- jasper version: 0.1.1 (purchased on App Store)
- GHE: http://our-ghe/ (not https)
- screen shot
 - ![e859bab6aa71f23bd57030c0a8ac754a](https://cloud.githubusercontent.com/assets/7099383/15886521/7e4bd350-2d98-11e6-97e6-f83fd8413c17.png)

**Comment by h13i32maru** [comment]
Hi! Thanks for this issue.

Please enter ``our-ghe`` instead of ``http://our-ghe``. And Jasper only supports https access to ghe. Is you GHE environment HTTPS?

**Comment by h13i32maru** [comment]
> GHE: http://our-ghe/ (not https)

Oh... Now, Jasper only supports https. However in next version I will support http.

**Comment by hdkshjm** [comment]
OK.
I'm looking forward to the next version.

**Comment by h13i32maru** [comment]
@hdkshjm I released Jasper v0.1.2. It supports HTTP of GHE. Please update and try using!

**Comment by hdkshjm** [comment]
Sorry for late.

Thanks for update!
I can setup without HTTPS option, but below screen displays...
![8249b13c19b26482969c52c74eff2433](https://cloud.githubusercontent.com/assets/7099383/16406052/ceb56a3c-3d46-11e6-8128-879f65d59b20.png)

Can you tell me the jasper log dir?
I will check jasper log file on my machine.

**Comment by hdkshjm** [comment]
@h13i32maru sorry, is it better to create another issue?

**Comment by h13i32maru** [comment]
> @h13i32maru sorry, is it better to create another issue?

Yes, please create another issue 🙇
