### ISSUE TITLE
Avatars not loading

### ISSUE THREAD

**Issue by nbelisle11** [jasperapp/jasper#213]
In the network console I can see a request going to 

```
https://<GHE-domain>/avatars/u/<id>?u=<redacted>
Request Method: GET
Status Code: 302 Found
```
And then a follow up request going to
```
https://<GHE-domain>/login?return_to=https%3A%2F%2F<GHE-domain>%2Favatars%2Fu%2F<id>%3F
Request Method: GET
Status Code: 200
```

Seems like it's not handling the auth properly when fetching avatars. The result is a lot of broken images
<img width="619" alt="Jasper" src="https://user-images.githubusercontent.com/5873903/128786043-a7cd7413-7522-4df3-b63f-b489a2d32f7b.png">

**Comment by mactkg** [comment]
Same issue is happened at my environment. We use GHE 3.0.x

**Comment by mactkg** [comment]
@nbelisle11 
I have encountered same issue.  What version of GHE do you use?  I use 3.0.x.

**Comment by mgatespot** [comment]
same, seems like a dead project :(

**Comment by mactkg** [comment]
I think Jasper may work with older versions of GHE... 
Does it works with GHE2.x? I don't have an environment to test but I suspect an undocumented change of GHE.

**Comment by mgatespot** [comment]
i'm using version 3.0 🤔

**Comment by brianDoherty** [comment]
@h13i32maru it appears that this issue come back. Running into similar 302 redirects for avatars when using with github enterprise.
