### ISSUE TITLE
Getting incorrect notifications

### ISSUE THREAD

**Issue by davidcelis** [jasperapp/jasper#22]
I'm not sure why, but Jasper doesn't appear to be showing me any of the content I'd expect to be seeing. For example, right now:

* Jasper tells me I have one unread item
* This item is in the "Me" tab under "System" in the sidebar
* I am *not currently subscribed* to this item. When I visit it, the in-app web browser correctly shows "You’re not receiving notifications from this thread."
* Visiting it subsequently marks the issue as read
* Within a minute, the issue _re-appears_ in my "Me" inbox even though _nothing new has happened_. In fact, this issue has not been touched since late September.
* If I make an API request to `https://api.github.com/search/issues?q=involves:davidcelis`, this issue is not listed.

Meanwhile, on github.com's web interface I have several unread notifications that simply do not appear anywhere in Jasper. API requests to `api.github.com/notifications`, however, correctly show them.

What API requests is Jasper making to get notifications? And why would items unrelated to me appear under "Me"?

**Comment by h13i32maru** [comment]
Hi.

> Meanwhile, on github.com's web interface I have several unread notifications that simply do not appear anywhere in Jasper. API requests to api.github.com/notifications, however, correctly show them.

Jasper does not use notification API(`api.github.com/notifications`). Jasper uses search API(`api.github.com/search/issues`). So, Jasper does not sync notifications in github.com.

> What API requests is Jasper making to get notifications?

`Me` tab uses the URLs.
- `https://api.github.com/search/issues?per_page=100&page=1&sort=updated&order=desc&q=involves:davidcelis`
- `https://api.github.com/search/issues?per_page=100&page=1&sort=updated&order=desc&q=user:davidcelis`

You can see web interface.
- https://github.com/search?o=desc&q=involves%3Adavidcelis&s=updated&type=Issues&utf8=%E2%9C%93
- https://github.com/search?o=desc&q=user%3Adavidcelis&s=updated&type=Issues&utf8=%E2%9C%93

If you use Jasper on Mac, you can exec `/Applications/Jasper.app/Contents/MacOS/Jasper` and watch request logs in console.

> And why would items unrelated to me appear under "Me"?

If possible, please tell me the issues. I will inspect it.

**Comment by davidcelis** [comment]
Unfortunately, it's an issue in a private repository, so you won't be able to view it. I'll keep an eye on this behavior and see if a public example ever happens.

**Comment by h13i32maru** [comment]
OK.
I close this issue. If necessary, please feel free reopen this issue.

**Comment by davidcelis** [comment]
Thanks @h13i32maru.

> So, Jasper does not sync notifications in github.com.

Would you accept a feature request for notifications? Being able to read notifications via Jasper (and possibly filter them into streams) would be really useful.

**Comment by h13i32maru** [comment]
> Would you accept a feature request for notifications? Being able to read notifications via Jasper (and possibly filter them into streams) would be really useful.

Already I have plan to support the feature(sync notification) 😄
