### ISSUE TITLE
label query does not work for private repository?

### ISSUE THREAD

**Issue by ohbarye** [jasperapp/jasper#25]
Hello @h13i32maru san. Thanks for the great app.

I recently found one of my streams has nothing inspite of the fact that I confirmed a query I was using was correct with "Preview" page.

The query is just as like below. (No more condition is specified as of now.)

```
label:"bug"
```

And that happens only when I expect the query to work for **private** repositories. Even though another queries for my public repo (e.g. just "repo:user/public-repo") work fine.

**Comment by h13i32maru** [comment]
@ohbarye Thanks. I will inspect it.

**Comment by h13i32maru** [comment]
Please check v0.2.4-beta.2. Probably I will fix the bug.
https://jasperapp.io/beta.html

**Comment by ohbarye** [comment]
@h13i32maru 
The version works well on my end. Thank you!
Shall I close this issue?

**Comment by h13i32maru** [comment]
Thanks!
