### ISSUE TITLE
Cannot import issues

### ISSUE THREAD

**Issue by saga-dash** [jasperapp/jasper#278]
I have been unable to import issues since about 1/28.
The cause of the error is that timelineItems.nodes in RemoteGitHubV4IssueEntity contains null.

1/28頃からissueが取り込めなくなりました。
エラーの原因はRemoteGitHubV4IssueEntity の timelineItems.nodes にnull が含まれることによる。

<img width="483" alt="スクリーンショット 2023-02-01 12 29 06" src="https://user-images.githubusercontent.com/2353502/215954065-f977dee5-9be6-4f82-ac97-db2dcf56ea08.png">

LoggerFragment
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/2353502/215953496-4b9ff2c6-af25-4077-b937-cff298efa476.png">

DevTools(Main)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/2353502/215953923-4ef7d2b3-25c8-47f3-8284-bd2c22489e20.png">

---

Jasper Version: 1.1.2
Laptop: M2 Mac
OS: macOS Ventura 13.2

**Comment by h13i32maru** [comment]
PRありがとうございます。

こちら、エラーとしてはProjectNextAPIを使用しているからのはずなのですが、現在JasperではそのAPIは使ってないので根本的な原因が不明です。もし深堀りの調査が可能でしたらお願いしたいです。僕の手元では再現せず調査が難しいです（同僚が再現してるんですがやはり原因がわからず）。

仮説としてはGraphqlのTimelineItemsを取得してる中のクエリで、いずれかのオブジェクトがgithub内部的にはProjectNextAPIを触るようになってしまった or github側の不具合では？と思っています。

追加の情報等あればよろしくお願いします。

**Comment by saga-dash** [comment]
GraphQLもGitHub GraphQL APIも詳しくありませんが [プロジェクトを含むissue](https://github.com/saga-dash/jasper/issues/1) を立てて検証したところ

- 1/27以前？はprojectItemsのみに入っていたものがtimelineItemsに含まれる変更があった？
- しかしResolver？でエラーになりtimelineItemsにはnull、errorsにはNOT_FOUNDが入った

ように見えました。

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2353502/216494978-d5b984de-f0a2-4df9-b111-b74019f6dbdf.png">

<details>

https://docs.github.com/ja/graphql/overview/explorer

```
query { 
  node(id: "I_kwDOI4VLD85dhgcn") {
    id,
    ... on Issue {
      projectItems(first: 100) {
        nodes {
          id
        }
      }
      timelineItems(first: 100) {
        nodes {
          __typename
        }
      }
    }
  }
}
```
</details>

---

[changelog](https://docs.github.com/ja/graphql/overview/changelog) にも [reference](https://docs.github.com/en/graphql/reference/unions#issuetimelineitems) にもとくに変更はなさそうに見えますね...

**Comment by h13i32maru** [comment]
@saga-dash 調査ありがとうございます！
クエリの結果から見ると、
- projectへの追加イベントがtimelineitemsに入るようになった（これは以前からかも？）
- 何故かそれがnullになってしまう（これは明らかにgithub側の不具合に見える）

うーん、時間あるときにgithubにissue報告しようと思います。
ご協力ありがとうございました！

**Comment by iwashitahga** [comment]
@h13i32maru 

いつも利用させていただいております。
さて、昨日まで大丈夫だったのですが本日急に issue が import できなくなり、エラーを辿っていたらこの issue にたどり着きました。
![image](https://github.com/user-attachments/assets/4816d05f-8cd8-4d25-912f-f15429a978a3)
![image](https://github.com/user-attachments/assets/fb0db38b-78fd-46a5-a97b-167b50d802cc)

github api の不具合な可能性もあると思いますが、こちらの issue 変更分を配布版のアプリにも取り込んでいただけると幸いです。
(手元ではエラーが起きなかったため、この issue 対応で治るものと考えております)

**Comment by iwashitahga** [comment]
こちら本日再現しましたので共有です。

```
Jasper Version: 1.1.2
Laptop: M2 Mac
OS: macOS Ventura 13.3
```

![image](https://github.com/user-attachments/assets/3fe1cebc-65ee-440d-b3ba-8c984b220d42)
