### ISSUE TITLE
A STREAMS icon float after "READ ALL"

### ISSUE THREAD

**Issue by suzuki** [jasperapp/jasper#29]
## Overview

- A STREAMS icon float after "READ ALL"
- Jasper 0.2.4-beta.6
    - I use a fullscreen mode.

## Scenario

1. Use right button click on STREAM icon.

<img width="310" alt="2017-01-26 09 43 06" src="https://cloud.githubusercontent.com/assets/10488/22315841/7ffafdc8-e3ac-11e6-8a4a-b9b3f230c6d7.png">

2. Select "Read All".
3. Click "OK" in modal.

<img width="431" alt="2017-01-26 09 43 16" src="https://cloud.githubusercontent.com/assets/10488/22315865/a6a6805a-e3ac-11e6-8409-60c8c06f45fb.png">

4. Mouse cursor move to STREAM area, the icon selected by step 1 is floated.

<img width="244" alt="2017-01-26 09 43 29" src="https://cloud.githubusercontent.com/assets/10488/22315871/ab598246-e3ac-11e6-9d2b-a1aa07f85468.png">

## Expected 

- Don't float the icon

## Similar problem

- https://github.com/jasperapp/jasper/issues/14

**Comment by h13i32maru** [comment]
Hi, thanks for this issue.

I will fix this on next version.

**Comment by h13i32maru** [comment]
v0.3.0 was out! Please check it.
https://jasperapp.io/release.html

**Comment by suzuki** [comment]
I checked new version.
It is comfortable to use! thank you!!
