### ISSUE TITLE
suggestion: Read All → Mark As Read

### ISSUE THREAD

**Issue by lestrrat** [jasperapp/jasper#31]
StreamsのRead All は「全部読む」（これから読む動作をするということを表す）ので、一瞬「これ、ウィンドウがたくさんあくのかな…？」と思いました。

動作的には"Mark As Read"（読んだことにする）がよろしい気がします。

**Comment by h13i32maru** [comment]
ありがとうございます！次のバージョンで修正します。

**Comment by h13i32maru** [comment]
v0.3.0 was out! Please check it.
https://jasperapp.io/release.html
