### ISSUE TITLE
0.2.5 - `Suppress notification from self posting` not working?

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [jasperapp/jasper#33]
About `Suppress notification from self posting` in ver 0.2.5 [release note](https://jasperapp.io/release.html)

If `self posting` means followings, it seems like not working. It just notify everything same as previous version.
- issue I created
- pr I created
- issue or pr comment I posted
- issue or pr comment I edited

**Comment by h13i32maru** [comment]
Hi, thanks for this issue.

The `suppress` means `posted and edited` on Jasper.
I will fix this bug on next version.

**Comment by h13i32maru** [comment]
v0.3.0 was out! Please check it.
https://jasperapp.io/release.html

**Comment by mitsuyoshi-yamazaki** [comment]
@h13i32maru Hi, I just updated Japer to v0.3.0 but I don't think the issue is fixed.

> The suppress means posted and edited on Jasper.

I tested:
- creating issue (with assigning myself)
- editing issue description (of the issue I just created)
- posting comments (to the issue I just created)

and Jasper does notify everything.
Aren't those actions included in `posted and edited` ?

**Comment by h13i32maru** [comment]
for now, Jasper **can not** suppress creating a issue and a pr.

Jasper suppresses posting comment and editing comment on exist a issue and apr.

thanks.

**Comment by mitsuyoshi-yamazaki** [comment]
understood.
thanks
