### ISSUE TITLE
Doesn't Show GitHub Notifications

### ISSUE THREAD

**Issue by dodekeract** [jasperapp/jasper#35]
I'm subscribed to some repos via the GitHub `[watch]` functionality. Unfortunately Jasper doesn't seem to show my notifications in my inbox. Is this a bug? I expected it to replace and improve on GitHub's own Notification Center, which quickly becomes garbage with a lot of issues/notifications. Having 2 inboxes for 1 thing is a no-go for me.

**Comment by h13i32maru** [comment]
Hi, thanks for this issue.

It is a bug. I will fix it on next version.

**Comment by h13i32maru** [comment]
v0.3.0 was out! Please check it.
https://jasperapp.io/release.html

**Comment by dodekeract** [comment]
@h13i32maru Thanks, I'll check it out and re-open if needed.
