### ISSUE TITLE
In browser search not working on Ubuntu

### ISSUE THREAD

**Issue by yshrsmz** [jasperapp/jasper#36]
Hi, thanks for the great app.

I'm not sure if this is officially supported feature, but on Mac I can use <kbd>cmd</kbd>+<kbd>F</kbd> to search in a page, but on Ubuntu <kbd>ctrl</kbd>+<kbd>F</kbd> does nothing.
It would be great if this is supported on both platform.

**Comment by h13i32maru** [comment]
Hi, thanks for this issue.

I will fix this bug on next version.

**Comment by h13i32maru** [comment]
v0.3.0 was out! Please check it.
https://jasperapp.io/release.html

**Comment by yshrsmz** [comment]
Thanks, it's working now!
