### ISSUE TITLE
Can't go back when link-text dropped to the application window.

### ISSUE THREAD

**Issue by nakajmg** [jasperapp/jasper#4]
jasperのウィンドウにハイパーリンク付きのテキストをドラッグ&ドロップすると、jasperのトップページに戻れない状態になります。

1. jasper内のブラウザ（右パネル）でissueなどを開く
1. ハイパーリンク付きのテキストをドラッグする
1. ドラッグしたリンクテキストをどこでもいいのでドロップする
1. jasperのウィンドウ全体でドロップされたリンクのページが開かれる

補足: 外部ブラウザからのドロップでも同じ状態になります

ナビゲーションの戻るなどが存在しない（ショートカットも効かない）ので、jasperのアプリケーションに戻れない状態になります。戻るにはアプリケーションの再起動しか手段がないように思います。

インブラウザでリンクをクリックしようとしたら誤ってドラッグしてしまい上記の状態に陥りました。

**Comment by h13i32maru** [comment]
@nakajmg Issue報告ありがとうございます。次のバージョン以降で修正します。

**Comment by h13i32maru** [comment]
@nakajmg さきほどJasper v0.1.2をリリースして、この不具合を修正しました！不具合報告ありがとうございました 😄
