### ISSUE TITLE
I want a dark theme

### ISSUE THREAD

**Issue by futabooo** [jasperapp/jasper#41]

**Comment by h13i32maru** [comment]
Please update to v0.4.0 and see [theme](https://jasperapp.io/theme.html)

**Comment by futabooo** [comment]
Cool!!

**Comment by barbequesauce** [comment]
I think this css needs to be updated?

<img width="750" alt="Screen Shot 2020-03-14 at 11 13 27 AM" src="https://user-images.githubusercontent.com/25070944/76684739-d6dd5600-65e4-11ea-8a5c-ce7fe110eb01.png">
