### ISSUE TITLE
Github no longer support Jasper's browser

### ISSUE THREAD

**Issue by dmnlk** [jasperapp/jasper#43]
![image](https://user-images.githubusercontent.com/909198/28855098-af62734a-7775-11e7-8ffe-a07c8b1696d4.png)

Please upgrade electron..

**Comment by yshrsmz** [comment]
+1
some controls(such as "Review Changes" button in PR view) are not working :thinking:

**Comment by dmnlk** [comment]
drop-down list menus are not working(ex: Watch menu)

**Comment by dmnlk** [comment]
https://twitter.com/h13i32maru/status/892642775069474816
Owner already seems to notice issue 👍

**Comment by yshrsmz** [comment]
It seems like GitHub has reverted the change

**Comment by h13i32maru** [comment]
> It seems like GitHub has reverted the change

Yes, GitHub reverted.
