### ISSUE TITLE
Buttons are effective only when clicking their glyph region.

### ISSUE THREAD

**Issue by yuya-oc** [jasperapp/jasper#48]
[![https://gyazo.com/fd427b8fc6e74e9fce4b707bc202aa53](https://i.gyazo.com/fd427b8fc6e74e9fce4b707bc202aa53.gif)](https://gyazo.com/fd427b8fc6e74e9fce4b707bc202aa53)

**Comment by h13i32maru** [comment]
Thanks!
I fixed this issue in v0.5.0-beta.1
Please check it https://jasperapp.io/beta.html
