### ISSUE TITLE
Google Chrome has blocked downloads.

### ISSUE THREAD

**Issue by hirak** [jasperapp/jasper#58]
- Google Chrome 67.0.3396.99（Official Build） （64 ビット）
- Mac OS Sierra 10.12.6

## How to reproduce

1. Open https://jasperapp.io/release.html?os=mac
2. Click "Download for Mac"

![image](https://user-images.githubusercontent.com/835251/42802800-edb1543c-89de-11e8-9688-837d81cf7689.png)

**Comment by cfrank** [comment]
I am able to follow those steps and it results in a successful download in Chrome on OSX:

- Google Chrome: Version 62.0.3202.75 (Official Build) (64-bit)
- OSX: 10.12.6
