### ISSUE TITLE
Badge icon

### ISSUE THREAD

**Issue by davidcelis** [jasperapp/jasper#6]
It'd be great if Jasper showed a badge on the Dock Icon with the number of unread notifications! Example:

![](https://cdn.davidcel.is/screens/Screen-Shot-2016-06-10-at-4.19.54-PM.png)

**Comment by h13i32maru** [comment]
@davidcelis Thanks for this proposal. I condier it!

**Comment by h13i32maru** [comment]
@davidcelis I released Jasper v0.1.2! It supports unread count on dock icon 😄  Please update and see preferences.
