### ISSUE TITLE
JIRA support

### ISSUE THREAD

**Issue by mycaule** [jasperapp/jasper#61]
Your tool is cool. Thank you.

Do you know if their is a similar app for JIRA or do you plan to support it as well ?
There are some CLI tools for JIRA available on GitHub already..

**Comment by janpio** [comment]
(Comment from a bystander)

Is JIRA's API similar to the Github API? I can't imagine. As Jasper is fully based on Github's API to retrieve and read issues and all their data, this would be a requirement to be able to adapt the app to support JIRA. 

Also, from my understanding, JIRA's data model of issues is much more complex (more fields, configurable fields) than the simple data model of Github's issues (title, text, labels, milestones - done) which would be another complication.

**Comment by mycaule** [comment]
OK I was thinking of an aggregation tool like Franz for messaging. https://meetfranz.com
Tough subject indeed.

As companies tend to use a combination of JIRA, GitHub, other CI Tools, I thought it would be nice to have a similar tool to Franz for developpers.

**Comment by janpio** [comment]
OT: Thanks for the octobox link, exactly what I was looking for I think ;)
