### ISSUE TITLE
Suppress notifications from self posting (not only from changes in Jasper)

### ISSUE THREAD

**Issue by andybergon** [jasperapp/jasper#63]
I know v0.3.0 fixed the self posting notifications in #33 but I was wondering if there is a way Jasper can check if a notification is relative to a change the logged user made and suppress those even if the changes were made outside the Jasper app.

This is a feature me and my colleagues would love!

**Comment by garrettw** [comment]
Agreed. I don't want Jasper to notify me when I myself comment on an issue I'm subscribed to.

**Comment by andybergon** [comment]
I guess fixed by: https://github.com/jasperapp/jasper/commit/211bf7fd5fc36e58ccfa2c9d3f700b7a52484e5a ?

**Comment by h13i32maru** [comment]
Yes, the commit fixed it.

**Comment by andybergon** [comment]
@h13i32maru I returned to receive those notifications on 1.0.2. Can you replicate?
