### ISSUE TITLE
Ability to resize built-in browser

### ISSUE THREAD

**Issue by mottox2** [jasperapp/jasper#8]
Hi,

I feel build-in browser scale is too big. I always use github 90% scale
I would like to resize built-in browser.

**Comment by h13i32maru** [comment]
@mottox2 Thanks and sorry for late response 😓 
I will try to implement the feature in future version.

**Comment by h13i32maru** [comment]
I released Jasper v0.2.0 at now! And support zoom screen.
Please download and use it 👍 
https://jasperapp.io/release.html

**Comment by whizark** [comment]
In my case, the default scale is too small, but the zoom screen support helps me too :smile:
Thank you for your improvements.

About the max zoom level, it is still a bit small for my screen (especially, for side panes).
It would be nice if Jasper has abilities to support more zoom level and save/restore the settings.

The max zoom level seems to be 125%, although I couldn't know it as we cannot (?) test `electron.webFrame.setZoom*()` on dev tools in Jasper.
I attach some screenshots below.

Default:
![jasper-1](https://user-images.githubusercontent.com/1211058/31208617-304922ba-a9c1-11e7-9b75-743174919a15.png)

Max:
![jasper-2](https://user-images.githubusercontent.com/1211058/31208616-3048c3ce-a9c1-11e7-96c9-2fbb3dcfedc8.png)

Environment:
* Ubuntu 16.04 LTS

BTW, shortcut keys for Issue (to archive it etc,), "Zoom +" etc. seems not to be work on Linux, although they are not big problems to me for now.
