### ISSUE TITLE
[Request] Please write the environment construction procedure

### ISSUE THREAD

**Issue by yshr446** [jasperapp/jasper#81]
I want to contribute to this project, but I can't find procedure for environment construction

Could you add it to README ? 🙇

**Comment by pocke** [comment]
You can find the documentation from DEVELOP.md.
https://github.com/jasperapp/jasper/blob/be63021e7497dfba97a4aa846c16198cbffa8f3f/DEVELOP.md

By the way, I think adding a link to the document into the README.md is good idea.

**Comment by yshr446** [comment]
> You can find the documentation from DEVELOP.md.

Thanks 🙇 

> By the way, I think adding a link to the document into the README.md is good idea.

Nice idea! I will add it & create PR 👍

**Comment by yshr446** [comment]
> I will add it & create PR 👍

@pocke 

Please review & merge when you have time 🙏 

https://github.com/jasperapp/jasper/pull/82

**Comment by pocke** [comment]
Thank you for your pull request! I'll review it, but I don't have a permission to merge. So I cannot merge it. Sorry.
