### ISSUE TITLE
Display issue tags in second column

### ISSUE THREAD

**Issue by tdsmith** [jasperapp/jasper#9]
Thanks for a neat app! It would be great to see the current tags on each issue in the second column, and to have affordances to filter on them.

**Comment by h13i32maru** [comment]
@tdsmith Thanks and sorry for late reply 😓 
I will try to implement the feature in future version.
Thanks!

**Comment by h13i32maru** [comment]
@tdsmith I released v0.2.1-beta.1 and support displaying labels in second column 😄 
https://jasperapp.io/beta.html
