### ISSUE TITLE
App crashes 2-3 times a day

### ISSUE THREAD

**Issue by aem** [jasperapp/jasper#95]
Not sure how to debug this (happy to dig in if given diagnostic instructions) - but about 2-3 times a day everything in the app except the in-app browser will go white and crash entirely, I'll stop receiving notifications, and then I'll have to quit and re-open the app. Often after reopening I'll get an alert that "Jasper has quit unexpectedly"

**Comment by kentarohorie** [comment]
I met a same problem.

**Comment by aem** [comment]
This now is happening closer to 6-8 times a day and has become a pretty major pain in my workflow. Would love to know how I can help diagnose

**Comment by yuri-tceretian** [comment]
I started encountering the same issue since I upgraded to MacOS Mojave. It either crashes with a crash report or just silently crashes panes (shows white screen) but keep displaying browser.

**Comment by r0hit-gupta** [comment]
I am facing the same problem.

**Comment by h13i32maru** [comment]
Please check v0.8.0-beta that updated Electron.
https://jasperapp.io/beta.html
