### ISSUE TITLE
Mentions in embedded browser cause keyboard shortcuts to be activated

### ISSUE THREAD

**Issue by yuri-tceretian** [jasperapp/jasper#96]
Version: 0.7.2
OS: MacOS

### Description of the bug
- Types symbol `@` and wait until autocomplete is displayed 
- choose any person and choose by pressing the key `Enter`. Autocomplete popup should hide.
- Continue typing and see how menus in the toolbar are being activated

**Comment by h13i32maru** [comment]
Please check v0.8.0-beta that fixed it.
https://jasperapp.io/beta.html
