### ISSUE TITLE
Navigation bar disappears after machine sleep/resume

### ISSUE THREAD

**Issue by keisukefukuda** [jasperapp/jasper#97]
I'm using Jasper on MacOS. Thank you so much for the great software. It makes my life much easier. 

Here's a small bug report.
After hibernation, Jasper's left side navigation pane disappears. 
The right pane (embedded browser pane), menu bar, and other parts of the application seemingly continue working.

![image](https://user-images.githubusercontent.com/18257/61925096-ad17e600-afa5-11e9-8bfa-49ff6c344c62.png)

Thanks!

**Comment by r0hit-gupta** [comment]
@keisukefukuda we all are facing the same issue. https://github.com/jasperapp/jasper/issues/95

**Comment by keisukefukuda** [comment]
@r0hit-gupta Thanks. I'm closing my duplicated issue.

**Comment by h13i32maru** [comment]
Please check v0.8.0-beta that fixed it.
https://jasperapp.io/beta.html

**Comment by keisukefukuda** [comment]
Thanks! I'm using the beta version and I don't see the error so far!
